# ConfigurationDB
spring:
  servlet:
        multipart:
          max-file-size: 200MB
          max-request-size: 200MB
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ou-journal-db
    username: root
    # password: mai2604
    # password: IamPhong89
    password: Admin@123

    # url: jdbc:mysql://mysql-container:3306/ou-journal-db
    # username: pla
    # password: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: pladevspace@gmail.com
    password: kriu znmd svmi iibr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

#JPA/Hibernate
server:
  error:
    include-message: always
  # servlet:
  #   context-path: /social_network


#Logging
logging:
  level:
    root: info
    org:
      springframework:
        security: INFO
